baseURL: "http://www.xiaozefeng.xyz/"
languageCode: "en-us"
title: "xiaozefeng's blog"
theme: "hyde"
params: 
# themeColor: "theme-base-09"
  disqusShortname: spf13
  layoutReverse: false 
  #taxonomies:
  # tag: "tags"
  #category: "categories"
  #series: "series"

  paginate: 10
  paginatePath: page
  enableRobotsTXT: true
